run-dist:
		./build/install/app/bin/app
build:
	./gradlew clean build
run-install:
	./gradlew clean install
test:
	./gradlew test
report:
	./gradlew jacocoTestReport
lint:
	./gradlew checkstyleMain
run-h:
	./build/install/app/bin/app -h

.PHONY: build
.PHONY: test